class Persistent {
  static List<String> jobCategoryList = [
    "Accounting/Finance",
    "Administrative",
    "Advertising/Marketing",
    "Agriculture",
    "Architecture",
    "Arts/Entertainment/Publishing",
    "Banking",
    "Construction/Facilities",
    "Customer Service",
    "Education/Training",
    "Engineering",
    "Government/Military",
    "Healthcare",
    "Hospitality/Travel",
    "Human Resources",
    "Information Technology",
    "Insurance",
    "Legal",
    "Manufacturing/Production",
    "Media",
    "Nonprofit/Volunteer",
    "Real Estate",
    "Restaurant/Food Service",
    "Retail",
    "Sales",
    "Telecommunications",
    "Transportation/Logistics",
    "Other",
    // Additional categories
    "Automotive",
    "Biotech",
    "Consulting",
    "Design",
    "Distribution/Shipping",
    "Executive",
    "Facilities",
    "General Business",
    "Healthcare",
    "Human Resources",
    "Information Technology",
    "Installation/Maintenance/Repair",
    "Insurance",
    "Inventory",
    "Legal",
    "Management",
    "Manufacturing/Production",
    "Marketing",
    "Nonprofit",
    "Pharmaceutical/Biotech",
    "Professional Services",
    "Purchasing/Procurement",
    "Quality Assurance/Safety",
    "Research",
    "Retail",
    "Sales",
    "Science",
    "Skilled Labor/Trades",
    "Strategy/Planning",
    "Supply Chain",
    "Telecommunications",
    "Training",
    "Transportation",
    "Warehouse",
  ];
}
