// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBDH7UxZiYpZR7N4JeH2rHun3OtZDntwKQ',
    appId: '1:229725611532:web:d390460ced0701a008b029',
    messagingSenderId: '229725611532',
    projectId: 'flutter-job-app-3aa75',
    authDomain: 'flutter-job-app-3aa75.firebaseapp.com',
    storageBucket: 'flutter-job-app-3aa75.appspot.com',
    measurementId: 'G-XGCJEHPW98',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCzhguwUtrhKRYs0mpq7ZAnmsc8XpvbNtM',
    appId: '1:229725611532:android:0910683a02c2d57908b029',
    messagingSenderId: '229725611532',
    projectId: 'flutter-job-app-3aa75',
    storageBucket: 'flutter-job-app-3aa75.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAxlDeFswV_M2xZZ4BmlFbnC1un8sl0l7I',
    appId: '1:229725611532:ios:bc418cf91f31926408b029',
    messagingSenderId: '229725611532',
    projectId: 'flutter-job-app-3aa75',
    storageBucket: 'flutter-job-app-3aa75.appspot.com',
    iosBundleId: 'com.example.flutterJobApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAxlDeFswV_M2xZZ4BmlFbnC1un8sl0l7I',
    appId: '1:229725611532:ios:9747b15bfcdba5ba08b029',
    messagingSenderId: '229725611532',
    projectId: 'flutter-job-app-3aa75',
    storageBucket: 'flutter-job-app-3aa75.appspot.com',
    iosBundleId: 'com.example.flutterJobApp.RunnerTests',
  );
}
